// examples/demo-next/components/Counter.tsx
"use client";

import { useState } from "react";

interface Props {
	initial?: number;
	children?: React.ReactNode;
}

function Counter({ initial = 0 }: Props) {
	const [count, setCount] = useState(initial);

	return (
		<div className="counter-card">
			<div className="counter-display">
				<div className="counter-value">{count}</div>
				<p className="counter-label">Count</p>
			</div>
			<div className="counter-controls">
				<button
					className="btn btn-secondary"
					onClick={() => setCount((c) => c - 1)}
					aria-label="Decrease count"
					type="button"
				>
					−
				</button>
				<button
					className="btn btn-secondary"
					onClick={() => setCount(initial)}
					aria-label="Reset count"
					type="button"
				>
					Reset
				</button>
				<button
					className="btn btn-primary"
					onClick={() => setCount((c) => c + 1)}
					aria-label="Increase count"
					type="button"
				>
					+
				</button>
			</div>
		</div>
	);
}

// Default export required — the docvia registry imports this via dynamic path
export default Counter;

// examples/demo-svelte/src/lib/components/Counter.svelte
<script lang="ts">
interface Props {
	initial?: number;
}

const { initial = 0 }: Props = $props();
// svelte-ignore state_referenced_locally
let count = $state(initial);
</script>

<div class="counter-card">
  <div class="counter-value">{count}</div>
  <p class="counter-label">Count</p>

  <div class="counter-controls">
    <button
      class="btn"
      onclick={() => count--}
      aria-label="Decrease count"
    >
      −
    </button>
    <button
      class="btn"
      onclick={() => (count = initial)}
      aria-label="Reset count"
    >
      Reset
    </button>
    <button
      class="btn btn-primary"
      onclick={() => count++}
      aria-label="Increase count"
    >
      +
    </button>
  </div>
</div>
