// packages/cli/templates/sveltekit/src/routes/docs/DocsTree.svelte
<script lang="ts">
	import type { PageTree } from '@docvia/source';
	import DocsFolder from './DocsFolder.svelte';

	let { nodes, activePath }: { nodes: PageTree.Node[]; activePath: string } = $props();
</script>

<ul>
	<!-- Separators and folders have no id, and siblings may share a name. -->
	{#each nodes as node, i (node.type === 'page' ? node.url : `${node.type}-${i}`)}
		<li>
			{#if node.type === 'page'}
				<a href={node.url} aria-current={activePath === node.url ? 'page' : undefined}>
					{node.name}
				</a>
			{:else if node.type === 'folder'}
				<DocsFolder folder={node} {activePath} />
			{:else}
				<div class="docs-folder">{node.name}</div>
			{/if}
		</li>
	{/each}
</ul>

// packages/cli/templates/react/components/docs-tree.tsx
import type { PageTree } from "@docvia/source";

/** The sidebar: pages, folders and separators from `source.pageTree`. */
export function DocsTree({ nodes }: { nodes: PageTree.Node[] }) {
	return (
		<ul>
			{nodes.map((node) => (
				<li key={node.type === "page" ? node.url : node.name}>
					{node.type === "page" ? (
						<a href={node.url}>{node.name}</a>
					) : node.type === "folder" ? (
						<>
							<div className="docs-folder">
								{node.index ? (
									<a href={node.index.url}>{node.name}</a>
								) : (
									node.name
								)}
							</div>
							<DocsTree nodes={node.children} />
						</>
					) : (
						<div className="docs-folder">{node.name}</div>
					)}
				</li>
			))}
		</ul>
	);
}
